
name: Build-And-Deploy

on:
  push:
    branches: [ master ]
  release:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.event.release.prerelease }}
        echo ${{ github.event.release.prerelease == false }}
        echo ${{ !github.event.release.prerelease && github.event_name == 'released' }}
        echo ${{ github.event.release.prerelease == false && github.event_name == 'released' }}
        echo ${{ github.event.release.prerelease == false && github.event_name == 'released' }}
  setup0:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease }}
    steps:
    - name: debug
      run: |
        echo ${{ github.event.release.prerelease }}
        
  setup1:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease }}
    steps:
    - name: debug
      run: |
        echo ${{ github.event.release.prerelease }}
