
name: Build-And-Deploy

on:
  push:
    branches: [ master ]
  release:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      run: |
        echo ${{ github.event.release.prerelease }}
        
    - name: Cluster env for production
      if: (!github.event.release.prerelease && github.event_name == 'released')
      run: |
        echo ::set-env name=CLUSTER_ENV::prod
        echo prod
        
    - name: Cluster env for staging/dev
      if: (github.event.release.prerelease && github.event_name == 'released')
      run: |
        echo dev
